# Write your MySQL query statement below
SELECT USER_ID, COUNT(*) AS PROMPT_COUNT, ROUND(AVG(TOKENS),2) AS AVG_TOKENS
FROM PROMPTS
GROUP BY USER_ID
HAVING COUNT(*)>=3
AND MAX(TOKENS)>AVG(TOKENS)
ORDER BY AVG_TOKENS DESC,USER_ID ASC; 