# Write your MySQL query statement below
SELECT SAMPLE_ID, DNA_SEQUENCE, SPECIES,
CASE
    WHEN DNA_SEQUENCE LIKE 'ATG%' THEN 1 
    ELSE 0
END AS HAS_START,

CASE
    WHEN DNA_SEQUENCE LIKE '%TAA' OR DNA_SEQUENCE LIKE '%TAG' OR DNA_SEQUENCE LIKE '%TGA' THEN 1 
    ELSE 0
END AS HAS_STOP,

CASE
    WHEN DNA_SEQUENCE LIKE '%ATAT%' THEN 1 
    ELSE 0
END AS HAS_ATAT,

CASE
    WHEN DNA_SEQUENCE LIKE '%GGG%' THEN 1 
    ELSE 0
END AS HAS_GGG

FROM SAMPLES;